### ISSUE TITLE
Support for auto open/close tags

### ISSUE THREAD

**Issue by kemmerly** [tpmatthes/Twig.novaextension#1]
It would be great to be able to just start typing if, for, etc and tab to get the full code with surrounding tags and end tag. This is possible in the Coda plugin for Twig.

Thanks for working on this extension.

**Comment by tpmatthes** [comment]
Hey, thanks for your suggestion! 😊

I’ve just released version 1.2 of the plugin, which adds support for matching brackets (`%}`) and tags (`{% endif %}` etc.) in tag completions. Example:

```twig
{# Type this #}
{% i

{# Get this #}
{% if [condition] %}[…]{% endif %}
```

Since I’m not familiar with the Coda plugin, I’d love to hear your thoughts: Does this solve your issue?

**Comment by kemmerly** [comment]
Thanks for the update! That is much more useful.

I'd love to also just be able to type "if" (without opening twig brackets) and get a dropdown to choose the if completion - like in the Coda plugin.

![image](https://user-images.githubusercontent.com/1459061/96280171-a78d2e00-0fa5-11eb-931a-a1767d7f75f7.png)

**Comment by tpmatthes** [comment]
Ah ok, thanks for the screenshot! I’ve copied the completions for basic Twig tags and created another completion set for Twig-HTML. The plugin actually has two syntax definitions: Twig-HTML (Twig code alongside regular HTML tags) and Twig (Twig code inside brackets). Basic tag completions are now available in Twig-HTML, too.

Another day, another release: Version 1.3 should make this possible. Can you try it one more time? 😄

**Comment by kemmerly** [comment]
Works great. Much appreciated since most of my projects use Twig.
