### ISSUE TITLE
Compatibility with Nova 10 Tree-sitter

### ISSUE THREAD

**Issue by studiomaiis** [tpmatthes/Twig.novaextension#12]
Hi Tim and thank you for your extension !

I had to revert to Nova 9.6 as Nova 10 introduced a new parsing library "Tree-sitter" : twig auto-completion stopped working (not working at all or poorly).

Do you have any plans to update the extension ?

**Comment by tpmatthes** [comment]
Hi Pierre,
thanks for taking the time to submit an issue!

There are no plans to update to Tree-sitter anytime soon as this would be a major rewrite. However, Nova still supports regex-based grammars. Here’s what Panic says about it:

> Note: With the introduction of [Tree Sitter](https://docs.nova.app/syntax-reference/tree-sitter) support in Nova 10, building new regex grammars is discouraged. Support will remain for the forseeable future for backward compatibility, but new features will be targeted exclusively at Tree Sitter.
— https://docs.nova.app/syntax-reference/regex-grammars/

Anyway, even with the introduction of Tree-Sitter, the syntax for completions remains the same. It should behave exactly like before. Which version of Nova did you use when you encountered this bug? It seems like there was an issue with completions in Nova < 10.3, but Panic eventually fixed it. See #11

Can you reproduce your issues with the latest version (Nova 10.4)?

**Comment by studiomaiis** [comment]
Thank you for your quick reply.

It works with 10.4 !

Sorry I didn't think about checking closed tickets... 
I submitted a bug to Panic when they released version 10. Funny they pointed me in your direction, and then fixed it ;-)

Thanks again for the extension !

**Comment by tpmatthes** [comment]
No problem! They never mentioned it in their changelog, so maybe they fixed it unknowingly … 😄
