### ISSUE TITLE
Pug extension?

### ISSUE THREAD

**Issue by dlewand691** [tpmatthes/Twig.novaextension#2]
Hello! This isn't an issue, but rather a request. I was hoping that Nova would support .pug files but it doesn't yet. Pug is similar to Twig and thought I'd reach out to see if you might be gracious enough to help create a pug version. I'm happy to help any way I can but not smart enough to start it from scratch. Thank you for indulging a layman's request! Cheers!

**Comment by tpmatthes** [comment]
Hey, thanks for reaching out! Unfortunately, I’m not familiar with Pug, but I can certainly share some things I’ve learned while working on this extension:

1. The official documentation is quite helpful: https://docs.nova.app/syntax-reference/
2. If you enable the extension developer menu, you can easily create a new extension folder from the menu.
3. Pug is a language that compiles into HTML, right? If Pug can’t be used alongside regular HTML code, the structure of this plugin is probably not ideal. The plugin actually has two syntax definitions: Twig-HTML (Twig code alongside regular HTML tags) and Twig (Twig code inside brackets). The same structure is used by the built-in PHP language definition. With that said, you can use a built-in language definition as your starting point. Right click on the “Nova” app in the Finder and select “Show content”. Then go to “Content/Shared Support/Extensions” and copy some extensions. You can probably use some definitions from ”JavaScript”, “HTML” or even “HAML”.
4. The syntax highlighting relies on regular expressions, which can be quite cumbersome, but it’s doable (with the help of an online tool).

I encourage you to try it! 👍 If you have any specific questions, feel free to contact me again. 😊
