### ISSUE TITLE
Tags in Twig comment blocks are not styled correctly

### ISSUE THREAD

**Issue by nyehughes** [tpmatthes/Twig.novaextension#4]
They show up as:
<img width="544" alt="Screenshot 2020-11-16 at 17 05 15" src="https://user-images.githubusercontent.com/3296602/99284242-ea088b80-282d-11eb-9555-50113967c6b0.png">

**Comment by tpmatthes** [comment]
Good catch! Version 1.4.1 should fix this issue. 👍
