### ISSUE TITLE
Nothing to report …

### ISSUE THREAD

**Issue by nofue** [tpmatthes/Twig.novaextension#5]
… but as there's no provision to hug you on Panic's site, I thought I'd make it an issue here. Thanks for this great Extension to Nova, works like a charm and far better than any other syntax-highlighting for TWIG I've ever used before. Awesome.

Thanks, 

Norbert

**Comment by tpmatthes** [comment]
Hey, thanks for your kind words! I really appreciate it. 😄

**Comment by nofue** [comment]
> Am 01.12.2020 um 18:42 schrieb Tim-Patrick Matthes <notifications@github.com>:
> 
> 
> Hey, thanks for your kind words! I really appreciate it. 😄
> 
> 

No worries — it’s so much more fun editing TWIG files with proper syntax marking, I’m just amazed. And I’m also amazed by Neon because of it’s plug-in architecture making things like this possible. I was about buying BB-Edit, but I think I’m rather going the Neon way as it also plays nicer with Transmit.

All the best and thanks again for sharing this gem, 

Norbert
