### ISSUE TITLE
Add support for Craft element queries

### ISSUE THREAD

**Issue by theskyfloor** [tpmatthes/Twig.novaextension#6]
Please add support for Craft element queries!

**Comment by theskyfloor** [comment]
Also amazing work thus far!

**Comment by tpmatthes** [comment]
Hey, thanks for your suggestion! Sounds like a good addition. You’re only referring to things like `craft.entries().[…]` and `craft.categories().[…]`, right? It’s probably not possible to add completions for custom fields, but we could drop in some additional methods as well.

The list of available methods for Craft element queries isn’t particularly short and maybe I need to find a way to hide them for regular Twig users. 🤔 I’ll definitely look into it, but it may take some time.

**Comment by theskyfloor** [comment]
Cool! Yeah right on... I use that with some Twig completion stuff for VSCode and it comes in handy.

**Comment by tpmatthes** [comment]
Turns out there’s a handy list for Element Queries on docs.craftcms.com; I’ve just added support for them + some common properties/methods. Can you update to version 1.6 and try it?

**Comment by theskyfloor** [comment]
Awesome! I can't seem to get it to work even though I'm on 1.6, any ideas? Whats the trigger for entries?

**Comment by tpmatthes** [comment]
Most completions should be visisble inside `{% … %}` or `{{ … }}` after a dot. Some completions need `craft.` or `entry.`, though.

![twig](https://user-images.githubusercontent.com/30212990/112046280-1caff100-8b4c-11eb-91cb-5d15cbbefdb7.png)

Does this work?

**Comment by tpmatthes** [comment]
Hey @theskyfloor, can you tell me, if this works for you? 😊

**Comment by theskyfloor** [comment]
It does work! Just finally tested it. I misunderstood the first time. These are brilliant! Even more helpful than completions in other editors for Craft. I was expecting more an autofill of a basic query but this is actually way more powerful and flexible. Thanks!!

**Comment by tpmatthes** [comment]
I’m happy that you’re enjoying the new feature, thanks for the feedback! 😊
